app/models.py
from . import db, login_manager
from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    firstname = db.Column(db.String(255),nullable=False)
    lastname = db.Column(db.String(255),nullable=False)
    username = db.Column(db.String(255), unique=True, nullable=False)
    email = db.Column(db.String(255), unique=True, nullable=False)
    secure_password = db.Column(db.String(255), nullable=False)
    profile_pic_path = db.Column(db.String())
    roles_id = db.Column(db.Integer, db.ForeignKey('roles.id'))

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.secure_password = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.secure_password, password)

    def save_u(self):
        db.session.add(self)
        db.session.commit()

    def _repr_(self):
        return f'User {self.username}'


class Admin (UserMixin, db.Model):
    __tablename__ = 'admin'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255), unique=True, nullable=False)
    email = db.Column(db.String(255), unique=True, nullable=False)
    secure_password = db.Column(db.String(255), nullable=False)
    profile_pic_path = db.Column(db.String())
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.secure_password = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.secure_password, password)

    def save_a(self):
        db.session.add(self)
        db.session.commit()

    def _repr_(self):
        return f'User {self.username}'


class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    users = db.relationship('User', backref='roles', lazy="dynamic")
    admin = db.relationship('Admin', backref='roles', lazy="dynamic")

    def _repr_(self):
        return f'User {self.name}'

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from config import config_options
from flask_login import LoginManager
from flask_mail import Mail
bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()
login_manager = LoginManager()
login_manager_session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config_name):
    app = Flask(__name__)
    #Create application configurations
    app.config.from_object(config_options[config_name])
    #Initializing Flask extensions
    bootstrap = Bootstrap(app)
    db.init_app(app)
    mail.init_app(app)
    login_manager.init_app(app)
    from . auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/authenticate')
    #Registering blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    return app

app/main/__init__.py
# from . import views
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from flask import render_template
from flask_login import login_required
# from app import create_app
from . import main 

@main.route('/')
def index():
    return render_template('index.html')

@main.route('/checkout')
def checkout():
    return render_template('checkout.html')

@main.route('/addcart')
@login_required
def cart():
    return render_template('cart.html')

app/templates/cart.html
 {% include 'navbar.html' %}
  {% include 'footer.html' %}
{%include 'bootstrap/base.html'%}
 <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='main.css') }}">

{% block content %}
 <main class="main-container">

     <section class="section">
         <h2 class="section-title">Products</h2>
         <div class="products">
             <div class="product">
                 <img class="product-image"
                     src="https://www.fmk.co.ke/wp-content/uploads/2019/08/Kale-Farmers-Market-Kenya.jpg" alt="Kales" />
                 <h2 class="product-name">Kales</h2>
                 <h3 class="product-price">100</h3>
                 <button class="btn btn-primary" data-action="add-to-cart">
                     Add To Cart
                 </button>
             </div>
             <div class="product">
                 <img class="product-image"
                     src="https://www.respectfood.com/wp-content/uploads/sites/2/2020/02/Spinach1.png" alt="Soinach" />
                 <h2 class="product-name">Spinach</h2>
                 <h3 class="product-price">5</h3>
                 <button class="btn btn-primary" data-action="add-to-cart">
                     Add To Cart
                 </button>
             </div>
             <div class="product">
                 <img class="product-image"
                     src="https://sokoshipafrica.com/wp-content/uploads/2020/11/coriander-hybrid-grade-a.jpg"
                     alt="Dania" />
                 <h2 class="product-name">Dania</h2>
                 <h3 class="product-price">5</h3>
                 <button class="btn btn-primary" data-action="add-to-cart">
                     Add To Cart
                 </button>
             </div>
             <div class="product">
                 <img class="product-image"
                     src="https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/full-frame-shot-of-broccoli-royalty-free-image-571248799-1532377854.jpg?crop=1.00xw:0.669xh;0,0.0641xh&resize=640:*"
                     alt="Broccoli" />
                 <h2 class="product-name">Broccoli</h2>
                 <h3 class="product-price">3</h3>
                 <button class="btn btn-primary" data-action="add-to-cart">
                     Add To Cart
                 </button>
             </div>
             <div class="product">
                 <img class="product-image" src="https://cdn.britannica.com/24/174524-050-A851D3F2/Oranges.jpg"
                     alt="Oranges" />
                 <h2 class="product-name">Oranges</h2>
                 <h3 class="product-price">200</h3>
                 <button class="btn btn-primary" data-action="add-to-cart">
                     Add To Cart
                 </button>
             </div>
             <div class="product">
                 <img class="product-image" src="https://gigi-gelato.com/wp-content/uploads/2020/05/mango-is-gezond.jpg"
                     alt="Mangoes" />
                 <h2 class="product-name">Mangoes</h2>
                 <h3 class="product-price">40</h3>
                 <button class="btn btn-primary" data-action="add-to-cart">
                     Add To Cart
                 </button>
             </div>
             <div class="product">
                 <img class="product-image"
                     src="https://images.everydayhealth.com/images/diet-nutrition/all-about-bananas-nutrition-facts-health-benefits-recipes-and-more-rm-722x406.jpg"
                     alt="Banana" />
                 <h2 class="product-name">Banana</h2>
                 <h3 class="product-price">5</h3>
                 <button class="btn btn-primary" data-action="add-to-cart">
                     Add To Cart
                 </button>
             </div>
             <div class="product">
                 <img class="product-image"
                     src="https://hips.hearstapps.com/clv.h-cdn.co/assets/15/22/1432664914-strawberry-facts1.jpg"
                     alt="Strawberry" />
                 <h2 class="product-name">Strawberry</h2>
                 <h3 class="product-price">200</h3>
                 <button class="btn btn-primary" data-action="add-to-cart">
                     Add To Cart
                 </button>
             </div>
             <div class="product">
                 <img class="product-image"
                     src="https://www.firstforwomen.com/wp-content/uploads/sites/2/2021/06/Whole-carrots.jpg"
                     alt="carrots" />
                 <h2 class="product-name">Carrots</h2>
                 <h3 class="product-price">250</h3>
                 <button class="btn btn-primary" data-action="add-to-cart">
                     Add To Cart
                 </button>
             </div>
         </div>
     </section>
     <section class="section">
         <h2 class="section-title">Cart</h2>
         <div class="cart">

         </div>
         <div class="cart-footer">
             <h2 class="cart-footer-total" data-action="total-price">1</h2>
             <button class="btn btn-primary btn-small btn-danger"><a href="{{url_for('main.index')}}">Go Back to homepage</a></button>
             <!-- <button class="btn btn-primary btn-small btn-danger" data-action="checkout" id="checkout">Checkout</button> -->
         </div>
     </section>
     <div id="information">
         <p>Your order will be processed and delivered within one hour of placing.</p>
         <p>Make sure you have the total amout for the order during order delivery delivery.</p>
         <p>Incase of any comment of complaint, Please reach out to us as fast as possible.</p>
         <p id="regards">Regards, Management</p>
     </div>
 </main>
 <script src="{{ url_for('static', filename='script.js') }}"></script>
 <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
     integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs=" crossorigin="anonymous"></script>

 {% endblock%}

app/templates/checkout.html
{%extends 'bootstrap/base.html'%}
{% include 'navbar.html' %}

{%block content%}
<div class="container">
    <div class="row">
        <div class="col-md-3">

        </div>
        <div class="col-md-6">
            <h2 class="text-center">CHECKOUT TABLE</h2>
            <table class="table bg-info">
                <thead class="text-center">
                    <th scope="col">No.</th>
                    <th scope="col">Item</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Price</th>
                    <th scope="col">Total</th>
                </thead>
                <tr>
                    <td>DataOne</td>
                    <td>DataTwo</td>
                    <td>DataThree</td>
                    <td>DataFour</td>
                    <td>DataFive</td>
                </tr>
            </table>
            <button class="btn btn-danger btn-lg">Cancel</button>
            <button class="btn btn-success btn-lg">Purchase</button>
        </div>
        <div class="col-md-3">

        </div>
    </div>

</div>

{%endblock%}

app/templates/footer.html
<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='style.css') }}">
<div class="footer">Mama Mboga@2021</div>

app/templates/index.html
{%include 'bootstrap/base.html'%}
{% include 'footer.html' %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='styles.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='bootstrap.css') }}">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
</script>
<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='bootstrap.min.css') }}">




<section>
    <background>
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
            </ol>
            <div class="carousel-inner" role="listbox">

                <div class="carousel-item active"
                    style="background-image: url('https://images.wallpaperscraft.com/image/tomato_twig_vegetable_108603_1920x1264.jpg')">
                    <div class="carousel-caption d-none d-md-block">
                        <h2 class="display-4">Mama Mboga</h2>
                        <p class="lead">The Best veges Under One Roof</p>
                        <a href="{{url_for('main.cart')}}"><button type="button" class="btn btn-outline-light">Let's
                                Eat!</button></a>
                    </div>
                </div>

                <div class="carousel-item">
                    <img src="{{url_for('static', filename='images/apples.jpg')}}" />
                    <div class="carousel-caption dia-none d-md-block">
                        <h2 class="display-4">Mama mboga</h2>
                        <p class="lead">The Richly grown.</p>
                        <a href="cart.html"><button type="button" class="btn btn-outline-light">Let's
                                Feast!</button></a>
                    </div>
                </div>

                <div class="carousel-item"
                    style="background-image: url('https://www.desktopbackground.org/p/2010/09/10/77505_download-wallpapers-3840x2160-lemon-leaf-white-backgrounds-4k_3840x2160_h.jpg')">
                    <div class="carousel-caption d-none d-md-block">
                        <h2 class="display-4">Mama Mboga</h2>
                        <p class="lead">Delicious to the seed</p>
                        <a href="cart.html"><button type="button" class="btn btn-outline-light">Let's
                                Eat!</button></a>
                    </div>
                </div>


                <div class="carousel-item">
                    <img src="{{url_for('static', filename='images/potatoes.jpg')}}" />
                    <div class="carousel-caption d-none d-md-block">
                        <h2 class="display-4">Mama Mboga</h2>
                        <p class="lead">For the Love of fruits.</p>
                        <a href="cart.html"><button type="button" class="btn btn-outline-light">Let's
                                Eat!</button></a>
                    </div>
                </div>

                <div class="carousel-item">
                    <img src="{{url_for('static', filename='images/kale.jpg')}}" />

                    <div class="carousel-caption d-none d-md-block">
                        <h2 class="display-4">Mama mboga</h2>
                        <p class="lead">Powered by Veges</p>
                        <a href="cart.html"><button type="button" class="btn btn-outline-light">Let's
                                Eat!</button></a>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </background>
</section>
<footer>

</footer>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs=" crossorigin="anonymous"></script>

<script src="{{url_for('static', filename='bootstrap.bundle.min.js')}}"></script>
{%endblock%}

app/templates/navbar.html
<div class="container">
    <div class="navbar navbar-dark" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"> MAMA MBOGA </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="btn btn-navbar btn-lg"id="buton"><a href="{{url_for('main.index')}}">Welcome</a> </li>
                   
                    <!-- <li class="btn btn-navbar btn-lg" id="buton"><a href="{{url_for('auth.register')}}">Sign Up</a>
                    </li> -->
                     {% if current_user.is_authenticated %}
                      <li class="user btn btn-navbar btn-lg"><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                   <li class="btn btn-navbar btn-lg" id="buton"><a href="{{url_for('main.cart')}}"><img
                               src="https://thumbs.dreamstime.com/z/shopping-cart-icon-vector-logo-137282150.jpg"
                               alt="Image" width="20px">Cart</a>
                   </li>
                   {% else %}
                   <li class="user btn btn-navbar btn-lg"><a href="{{url_for('auth.login')}}">Sign in</a></li>
                     {%endif%}

                </ul>

            </div>

        </div>
    </div>
</div>
<br>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <div class="row">
        <!-- displaying  Username-->
        <h3> {{user.username| capitalize}} </h3>
        <hr>
        <!--Display profile photo-->
        <div class="col-md-3">
            <div class="thumbnail">
                {% if user.profile_pic_path %}
                <img class="" src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
                {%else%}
                <p>No profile picture</p>
                {% endif %}

                {% if user == current_user %}
                <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post"
                    enctype="multipart/form-data">
                    <input type="file" name="photo" class="form-control" required>
                    <input type="submit">
                </form>
                {% endif %}
            </div>
        </div>
        <div class="col-md-9">
            <p>Name: {{user.firstname}} {{user.lastname}} </p>
            <p>No of piches: {{pitches}}</p>
            <p>Date joined: {{date}}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h3> Bio </h3>

            <!--Displaying user bio-->
            {% if user.bio %}
            <p> {{user.bio}}</p>
            {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
            {% endif %}

            {% if user == current_user %}
            <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    {{wtf.quick_form(form)}}
</div>
{% endblock %}